/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz_TriviaT;
import java.util.Vector;
import static trivia_tec.Trivia_TEC.juego;
import trivia_tec.*;

/**
 *
 * @author Gabriel
 */
public class VentanaParticipantes extends javax.swing.JFrame {

    
    Partida partida = new Partida();
    
    
    /**
     * Creates new form VentanaParticipantes
     * @param juego */
    public VentanaParticipantes(Trivia juego) {
        initComponents();
        errorCurso.hide();
        errorEstudiante.hide();
        errorMinimo.hide();
        señalAgregado.hide();
        juego.setPartida(partida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tCarne = new javax.swing.JTextField();
        bAgregar = new javax.swing.JButton();
        bEmpezar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bDificultad = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tCurso = new javax.swing.JTextField();
        errorCurso = new javax.swing.JLabel();
        errorEstudiante = new javax.swing.JLabel();
        errorMinimo = new javax.swing.JLabel();
        señalAgregado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresar carné participante:");

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEmpezar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bEmpezar.setText("EMPEZAR");
        bEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpezarActionPerformed(evt);
            }
        });

        jLabel2.setText("Dificultad:");

        bDificultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel3.setText("Código del curso:");

        tCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCursoActionPerformed(evt);
            }
        });

        errorCurso.setForeground(new java.awt.Color(255, 0, 0));
        errorCurso.setText("Curso no encontrado");

        errorEstudiante.setForeground(new java.awt.Color(255, 0, 0));
        errorEstudiante.setText("Estudiante no encontrado");

        errorMinimo.setForeground(new java.awt.Color(255, 0, 0));
        errorMinimo.setText("No hay suficientes jugadores");

        señalAgregado.setForeground(new java.awt.Color(0, 204, 0));
        señalAgregado.setText("(Agregado)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bEmpezar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAgregar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorEstudiante)
                            .addComponent(errorCurso)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tCarne)
                                .addComponent(tCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(errorMinimo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(señalAgregado)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(errorEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMinimo)
                .addGap(1, 1, 1)
                .addComponent(bAgregar)
                .addGap(4, 4, 4)
                .addComponent(señalAgregado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(bEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        
        Curso cur = juego.buscarCurso(tCurso.getText());
        if(cur!=null){
            boolean band = false;
            for(int i = 0; i<(cur.getEstMatriculados()).size(); i++){
                Estudiante actual = (Estudiante)(cur.getEstMatriculados()).get(i);
                if(actual.getCarne()==Integer.parseInt(tCarne.getText())){
                    Jugador nuevo = new Jugador(actual);
                    partida.registrar(nuevo);
                    partida.setCantParticipantes(partida.getCantParticipantes()+1);
                    señalAgregado.setText(actual.getNombre()+" listo para jugar!");
                    señalAgregado.setVisible(true);
                    band = true;
                }
                      
            }
            if(band == false)
                errorEstudiante.setVisible(true);
        }
        else
            errorCurso.setVisible(true);
        
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpezarActionPerformed
        // TODO add your handling code here:
        if(partida.getCantParticipantes()>=2){
            partida.setDificultad(bDificultad.getSelectedIndex()+1);
            partida.setNombre("Partida1");
            VentanaPreJuego pre = new VentanaPreJuego();
            pre.setVisible(true);
            this.setVisible(false);
        }
        else{
            errorMinimo.setVisible(true);
        }
    }//GEN-LAST:event_bEmpezarActionPerformed

    private void tCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaParticipantes(juego).setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JComboBox bDificultad;
    private javax.swing.JButton bEmpezar;
    private javax.swing.JLabel errorCurso;
    private javax.swing.JLabel errorEstudiante;
    private javax.swing.JLabel errorMinimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel señalAgregado;
    private javax.swing.JTextField tCarne;
    private javax.swing.JTextField tCurso;
    // End of variables declaration//GEN-END:variables
}
