/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz_TriviaT;
import java.util.Random;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import trivia_tec.*;
import static trivia_tec.Trivia_TEC.juego;



/**
 *
 * @author Gabriel
 */
public class VentanaPreJuego extends javax.swing.JFrame {

    
    /**
     * Creates new form VentanaPreJuego
     */
    public VentanaPreJuego() {
        initComponents();
        actualizarJugadores();
        actualizarTemas();
        pregunta.setVisible(false);
        tema.setVisible(false);
        
    }
    
    public void actualizarJugadores(){
        
        Partida actual = juego.getPartida();        
        Vector jugadores = actual.getParticipantes();        
        for(int i = 0; i<jugadores.size(); i++){
            Jugador temp = (Jugador) jugadores.get(i);
            while(i>=tJugadores.getRowCount()){
                DefaultTableModel model = (DefaultTableModel) tJugadores.getModel();
                Vector row = new Vector();
                row.add(null);
                model.addRow(row);
                
            }
            tJugadores.setValueAt(temp.getEstudiante().getNombre(), i, 0);
        }
        
    }
    public void actualizarTemas(){
        
        Partida actual = juego.getPartida();        
        Curso temp = juego.buscarCurso(VentanaParticipantes.tCurso.getText());
        Vector temas = temp.getTemas();
        for(int i = 0; i<temas.size(); i++){
            Tema tema = (Tema) temas.get(i);
            while(i>=tTemas.getRowCount()){
                DefaultTableModel model = (DefaultTableModel) tTemas.getModel();
                Vector row = new Vector();
                row.add(null);
                model.addRow(row);
                
            }
            tTemas.setValueAt(tema.getNombre(), i, 0);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tJugadores = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tTemas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bJugar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        pregunta = new javax.swing.JTextField();
        tema = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Jugadores"
            }
        ));
        jScrollPane3.setViewportView(tJugadores);

        tTemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Temas"
            }
        ));
        jScrollPane4.setViewportView(tTemas);

        jLabel1.setText("Es el turno de:");

        bJugar.setText("Jugar");
        bJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugarActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        pregunta.setText("jTextField2");

        tema.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bJugar)
                            .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(bJugar)
                        .addGap(70, 70, 70)
                        .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void seleccionarJugador(int i){
        
    }
    private void bJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugarActionPerformed
        // TODO add your handling code here:
        Curso temp = juego.buscarCurso(VentanaParticipantes.tCurso.getText());
        Random rand = new Random();
        int n = rand.nextInt(temp.getTemas().size());
        Tema temaRandom = (Tema) temp.getTemas().get(n);
        tema.setText(temaRandom.getNombre());
        
        int m = rand.nextInt(temaRandom.getPreguntas().size());
        Object preguntaRandom = temaRandom.getPreguntas().get(m);
        String clase = preguntaRandom.getClass().getName();
        
        if(clase.equalsIgnoreCase("trivia_tec.PreguntaFV")){
            VentanaJuegoFV juegoFV = new VentanaJuegoFV();
            juegoFV.setVisible(true);
            PreguntaFV preguntaFV = (PreguntaFV) preguntaRandom;
            pregunta.setText(preguntaFV.toString());
        }
        else if(clase.equalsIgnoreCase("trivia_tec.PreguntaSM")){
            VentanaJuegoSM juegoSM = new VentanaJuegoSM();
            juegoSM.setVisible(true);
            PreguntaSM preguntaSM = (PreguntaSM) preguntaRandom;
            pregunta.setText(preguntaSM.toString());
        }
        else if(clase.equalsIgnoreCase("trivia_tec.PreguntaSU")){
            VentanaJuegoSU juegoSU = new VentanaJuegoSU();
            juegoSU.setVisible(true);
            PreguntaSU preguntaSU = (PreguntaSU) preguntaRandom;
            pregunta.setText(preguntaSU.toString());
        }
          
    }//GEN-LAST:event_bJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new VentanaPreJuego().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField pregunta;
    private javax.swing.JTable tJugadores;
    public static javax.swing.JTable tTemas;
    private javax.swing.JTextField tema;
    // End of variables declaration//GEN-END:variables
}
